/* Brain Rocket — expert topics (level 3: mostly Hard, sometimes Medium). See data.js for the format. */
'use strict';

topic({ id: 'fabrics', name: 'Fabrics', noun: 'fabric', icon: '🧵', level: 3, q: 'Name a **type of fabric**.', strip: ['fabric'], list: `
1: Cotton, Wool, Silk, Denim, Leather, Polyester
2: Linen, Velvet, Nylon, Satin, Fleece, Lace, Corduroy, Cashmere, Lycra/Spandex/Elastane, Suede, Tweed, Flannel, Jersey, Chiffon, Felt, Canvas, Rayon/Viscose, Acrylic, Faux Fur, Fur
3: Tulle, Organza, Taffeta, Gingham, Tartan/Plaid, Chambray, Muslin, Calico, Poplin, Seersucker, Twill, Gabardine, Crepe, Georgette, Voile, Chenille, Terry/Terry Cloth/Towelling, Velour, Mohair, Angora, Alpaca, Merino, Lambswool, Hemp, Bamboo, Jute, Hessian/Burlap, Oilcloth, Gore-Tex, Neoprene, Microfiber/Microfibre, Polar Fleece, Sateen, Damask, Brocade, Jacquard, Tapestry, Chintz, Batik, Madras, Paisley, Houndstooth, Herringbone, Pinstripe, Oxford, Broadcloth, Duck Canvas, Ripstop, Mesh, Tencel/Lyocell, Modal, Acetate, PVC, Vinyl, Patent Leather, Nubuck, Sheepskin, Shearling, Moleskin, Interlock, Rib Knit/Ribbing, Cable Knit, Boucle
4: Shantung, Dupioni, Charmeuse, Habotai, Pongee, Crepe de Chine, Peau de Soie, Faille, Grosgrain, Moire, Barathea, Bengaline, Ottoman, Matelasse, Cloque, Ponte, Scuba, Loden, Melton, Boiled Wool, Donegal Tweed, Harris Tweed, Worsted, Serge, Whipcord, Cavalry Twill, Drill, Sailcloth, Crash, Huckaback, Dimity, Lawn, Batiste, Cambric, Organdy, Swiss Dot, Eyelet/Broderie Anglaise, Cheesecloth, Gauze, Buckram, Crinoline, Tarlatan, Marquisette, Ninon, Lame, Sequin Fabric, Cire, Panne Velvet, Crushed Velvet, Velveteen, Plush, Mink, Astrakhan/Karakul, Vicuna, Guanaco, Qiviut, Yak Wool, Camel Hair, Pashmina, Shahtoosh, Ramie, Sisal, Abaca, Pina, Kenaf, Coir, Modacrylic, Aramid/Kevlar, Nomex, Dyneema, Cordura, Tyvek, Polartec, Thinsulate, Spacer Mesh
5: Samite, Sendal, Fustian, Bombazine, Barege, Challis, Delaine, Grenadine, Mousseline, Zibeline, Peau d'Ange, Sharkskin, Tricotine, Shot Silk, Ikat, Kente, Bogolan/Mudcloth, Adire, Aso Oke, Kitenge, Kanga, Shweshwe, Tapa, Kalamkari, Bandhani, Khadi, Patola, Jamdani, Banarasi, Chanderi, Kanchipuram, Songket, Ulos, Tais, Barkcloth, Lampas, Tiraz, Byssus/Sea Silk, Spider Silk, Lotus Silk, Nettle Cloth
` });

topic({ id: 'gems', name: 'Gemstones', noun: 'gemstone', icon: '💎', level: 3, q: 'Name a **gemstone**.', list: `
1: Diamond, Ruby, Emerald, Sapphire, Pearl
2: Amethyst, Topaz, Opal, Jade, Turquoise, Garnet, Aquamarine, Amber, Onyx, Quartz, Rose Quartz, Peridot, Citrine, Moonstone, Tiger's Eye/Tigers Eye, Jasper, Agate, Lapis Lazuli/Lapis
3: Tourmaline, Tanzanite, Zircon, Cubic Zirconia, Spinel, Alexandrite, Morganite, Malachite, Obsidian, Hematite, Bloodstone, Carnelian, Chalcedony, Coral, Jet, Labradorite, Lepidolite, Rhodonite, Rhodochrosite, Sodalite, Sunstone, Amazonite, Aventurine, Fluorite, Smoky Quartz, Clear Quartz/Rock Crystal, Selenite, Kunzite, Iolite, Beryl, Chrysoberyl, Cat's Eye, Star Sapphire, Black Opal, Fire Opal, Pink Diamond, Blue Diamond, Moissanite, Mother of Pearl, Ametrine, Chrysoprase, Howlite, Pyrite/Fool's Gold, Unakite, Prehnite, Apatite, Kyanite, Larimar, Charoite, Sugilite, Azurite, Chrysocolla, Serpentine, Nephrite, Jadeite, Variscite, Ammolite
4: Paraiba Tourmaline, Watermelon Tourmaline, Rubellite, Indicolite, Tsavorite, Demantoid, Spessartine, Rhodolite, Pyrope, Almandine, Grossular, Hessonite, Uvarovite, Padparadscha, Benitoite, Taaffeite, Painite, Grandidierite, Red Beryl/Bixbite, Heliodor, Goshenite, Euclase, Jeremejevite, Musgravite, Poudretteite, Serendibite, Sphene/Titanite, Andalusite, Sillimanite, Diopside, Chrome Diopside, Enstatite, Hiddenite, Spodumene, Danburite, Phenakite, Scapolite, Sinhalite, Kornerupine, Cordierite, Axinite, Idocrase/Vesuvianite, Hemimorphite, Smithsonite, Dumortierite, Seraphinite, Moldavite, Libyan Desert Glass, Tektite, Petrified Wood, Conch Pearl, Melo Pearl, Tahitian Pearl, Akoya Pearl, South Sea Pearl, Keshi Pearl
5: Red Diamond, Pezzottaite, Kyawthuite, Hibonite, Bismutotantalite, Ekanite, Pollucite, Sapphirine, Vayrynenite, Clinohumite, Zektzerite, Parisite, Pallasite Peridot, Larvikite, Ussingite, Cavansite, Tugtupite, Eudialyte, Stichtite, Maw Sit Sit, Dendritic Agate, Thunder Egg, Binghamite
` });

topic({ id: 'bones', name: 'Bones', noun: 'bone in the body', icon: '🦴', level: 3, q: 'Name a **bone in the human body**.', strip: ['bone'], list: `
1: Skull, Ribs/Rib, Spine/Backbone, Femur/Thigh Bone, Collarbone/Clavicle, Jawbone/Jaw
2: Pelvis/Hip Bone, Kneecap/Patella, Shoulder Blade/Scapula, Tibia/Shin Bone/Shinbone, Fibula, Humerus/Funny Bone, Radius, Ulna, Sternum/Breastbone, Vertebrae/Vertebra, Tailbone/Coccyx, Mandible, Cranium
3: Maxilla, Sacrum, Carpals, Metacarpals, Phalanges, Tarsals, Metatarsals, Calcaneus/Heel Bone, Talus/Ankle Bone, Hyoid, Stapes/Stirrup, Incus/Anvil, Malleus/Hammer, Frontal Bone, Parietal Bone, Temporal Bone, Occipital Bone, Nasal Bone, Zygomatic/Cheekbone, Sphenoid, Ethmoid, Ilium, Ischium, Pubis, Atlas, Axis, Cervical Vertebrae, Thoracic Vertebrae, Lumbar Vertebrae, Floating Ribs
4: Scaphoid, Lunate, Triquetrum, Pisiform, Trapezium, Trapezoid, Capitate, Hamate, Navicular, Cuboid, Cuneiform/Medial Cuneiform, Lacrimal Bone, Palatine Bone, Vomer, Inferior Nasal Concha, Sesamoid, Xiphoid Process, Manubrium, Acromion, Coracoid, Olecranon, Malleolus, Trochanter
5: Fabella, Os Trigonum, Os Peroneum, Wormian Bones/Sutural Bones, Os Acromiale, Os Naviculare, Epipteric Bone, Os Vesalianum
` });

topic({ id: 'constellations', name: 'Constellations', noun: 'constellation', icon: '✨', level: 3, q: 'Name a **constellation**.', list: `
1: Orion, Big Dipper/The Plough/Plough, Ursa Major/Great Bear, Little Dipper, Ursa Minor/Little Bear
2: Cassiopeia, Leo, Scorpius/Scorpio, Taurus, Gemini, Cancer, Virgo, Libra, Sagittarius, Capricornus/Capricorn, Aquarius, Pisces, Aries, Pegasus, Southern Cross/Crux, Draco, Andromeda, Perseus, Hercules, Cygnus/Swan
3: Lyra, Aquila, Canis Major, Canis Minor, Bootes, Corona Borealis, Cepheus, Auriga, Centaurus, Lupus, Hydra, Ophiuchus, Serpens, Cetus, Eridanus, Lepus, Columba, Monoceros, Delphinus, Sagitta, Vulpecula, Corvus, Crater, Corona Australis, Triangulum, Lynx, Camelopardalis, Phoenix, Carina, Puppis, Vela, Ara, Pavo, Grus, Tucana
4: Antlia, Apus, Caelum, Chamaeleon, Circinus, Coma Berenices, Dorado, Equuleus, Fornax, Horologium, Hydrus, Indus, Lacerta, Leo Minor, Mensa, Microscopium, Musca, Norma, Octans, Pictor, Piscis Austrinus, Pyxis, Reticulum, Sculptor, Scutum, Sextans, Telescopium, Triangulum Australe, Volans, Canes Venatici
5: Argo Navis, Quadrans Muralis, Antinous, Noctua, Felis, Rangifer, Taurus Poniatovii, Cerberus, Machina Electrica, Officina Typographica, Globus Aerostaticus, Psalterium Georgii
` });

topic({ id: 'gods', name: 'Mythology', noun: 'Greek or Roman god', icon: '⚡', level: 3, q: 'Name a **Greek or Roman god or goddess**.', list: `
1: Zeus, Poseidon, Hades, Athena, Apollo, Aphrodite, Hermes, Ares, Jupiter, Mars, Venus, Neptune
2: Hera, Artemis, Demeter, Dionysus, Hephaestus, Hestia, Persephone, Eros, Cupid, Mercury, Pluto, Minerva, Juno, Diana, Vulcan, Bacchus, Ceres, Saturn, Cronus/Kronos, Gaia, Uranus, Nike, Hercules/Heracles, Atlas, Prometheus, Pan
3: Rhea, Hyperion, Helios, Selene, Eos, Nyx, Hecate, Iris, Hebe, Nemesis, Tyche, Hypnos, Thanatos, Morpheus, Asclepius, Hymen, Aeolus, Boreas, Zephyrus, Triton, Proteus, Nereus, Oceanus, Tethys, Themis, Mnemosyne, Metis, Leto, Dione, Janus, Vesta, Aurora, Sol, Luna, Fortuna, Bellona, Faunus, Flora, Pomona, Terminus, Quirinus, Somnus, Mors, Orcus, Proserpina, Liber, Victoria, Muses, Calliope, Clio, Erato, Euterpe, Melpomene, Polyhymnia, Terpsichore, Thalia, Urania, Fates/Moirai, Furies/Erinyes, Graces/Charites
4: Erebus, Chaos, Tartarus, Pontus, Ourea, Aether, Hemera, Eris, Ate, Momus, Oizys, Geras, Apate, Philotes, Achlys, Ananke, Chronos, Phanes, Coeus, Crius, Iapetus, Phoebe, Epimetheus, Menoetius, Astraeus, Pallas, Perses, Styx, Harmonia, Deimos, Phobos, Enyo, Eileithyia, Priapus, Aristaeus, Asteria, Palaemon, Leucothea, Amphitrite, Thetis, Doris, Galatea, Glaucus, Charon, Plutus, Kairos, Aion, Peitho, Pheme, Hesperus, Phosphorus, Notus, Eurus, Bona Dea, Lares, Penates, Genius, Picus, Silvanus, Vertumnus, Portunus, Consus, Ops, Tellus, Lucina, Carmenta, Egeria, Feronia, Libitina, Laverna, Mefitis, Sancus, Volturnus
5: Achelous, Alpheus, Anteros, Himeros, Pothos, Hedylogos, Hermaphroditus, Comus, Dolos, Horkos, Lyssa, Nomos, Hybris, Eupraxia, Eucleia, Euthenia, Euphrosyne, Aglaea, Zelos, Kratos, Bia, Arke, Aergia, Adephagia, Algos, Amechania, Elpis, Soteria, Telesphorus, Iaso, Panacea, Aceso, Hygieia, Epione, Rumina, Cardea, Fornax, Robigus, Pales, Mellona, Cloacina, Abundantia, Pietas, Concordia, Spes, Fides
` });

topic({ id: 'currencies', name: 'Currencies', noun: 'currency', icon: '💱', level: 3, q: 'Name a **currency**.', list: `
1: Dollar/US Dollar, Pound/Pound Sterling/British Pound, Euro, Yen, Bitcoin
2: Peso, Rupee, Franc/Swiss Franc, Yuan/Renminbi, Ruble/Rouble, Canadian Dollar, Australian Dollar, Krona, Krone, Won, Real, Rand, Lira, Dinar, Dirham, Riyal/Rial, Shekel, Baht, Ethereum
3: Zloty, Forint, Koruna, Leu, Lev, Kuna, Hryvnia, Lari, Dram, Manat, Tenge, Som, Somoni, Tugrik, Rupiah, Ringgit, Dong, Kip, Riel, Kyat, Taka, Afghani, Shilling, Naira, Cedi, Birr, Kwacha, Pula, Dalasi, Leone, Ariary, Kwanza, Metical, Lilangeni, Loti, Ouguiya, Nakfa, Sol, Bolivar, Boliviano, Guarani, Colon, Lempira, Cordoba, Quetzal, Balboa, Gourde, Escudo, Drachma, Mark/Deutsche Mark, Peseta, Guilder, Schilling, Penny/Pence, Cent, Dime, Nickel, Quarter, Sixpence, Farthing, Guinea, Crown, Sovereign, Ducat, Doubloon, Denarius, Sestertius, Dogecoin
4: Pataca, Ngultrum, Rufiyaa, Paanga, Tala, Vatu, Kina, Florin, Aruban Florin, Franc CFA/CFA Franc, Dobra, Ekwele, Syli, Zaire, Inti, Austral, Cruzeiro, Cruzado, Sucre, Markka, Punt, Lats, Litas, Kroon, Tolar, Karbovanets, Rentenmark, Reichsmark, Ostmark, Thaler, Groschen, Pfennig, Heller, Kreuzer, Gulden, Reis, Maravedi, Livre, Sou, Ecu, Louis d'Or, Napoleon, Noble, Angel, Groat, Solidus, Aureus, Obol, Talent, Mina, Daric, Tael, Cash, Mon, Ryo, Koban, Mohur, Anna, Paisa, Pie
5: Rai Stones/Rai, Wampum, Cowrie Shells/Cowries, Manilla, Kissi Penny, Katanga Cross, Tally Sticks, Hacksilver, Hyperinflation Pengo/Pengo, Bilpengo, Adopengo, Zimbabwe Dollar, Tical, Att, Fuang, Salung, Pya, Mu, Tiyin, Tyiyn, Luma, Tetri, Qindarka, Fils, Baisa, Halala, Khoums, Millime, Santim, Lisente, Thebe, Ngwee, Tambala, Kobo, Pesewa, Butut, Iraimbilanja, Sen, Jiao, Fen, Chon, Jeon, Mongo, Diram, Pul, Satang
` });

topic({ id: 'coding', name: 'Programming', noun: 'programming language', icon: '💻', level: 3, q: 'Name a **computer programming language**.', list: `
1: Python, JavaScript/JS, Java, C++/C Plus Plus/CPP, Scratch, HTML
2: C, C#/C Sharp, PHP, Ruby, Swift, Go/Golang, Rust, Kotlin, TypeScript, SQL, CSS, R, MATLAB, Visual Basic/VB, Basic, Assembly/Assembler, Lua, Perl, Dart, Bash/Shell
3: Haskell, Scala, Elixir, Erlang, Clojure, Lisp, Scheme, Racket, F#/F Sharp, OCaml, Julia, Fortran, COBOL, Pascal, Delphi, Ada, Objective-C, Groovy, PowerShell, Prolog, Smalltalk, Logo, Zig, Nim, Crystal, Elm, PureScript, CoffeeScript, Solidity, Apex, ABAP, SAS, Stata, VBA, Visual Basic .NET/VB.NET, ActionScript, Haxe, GDScript, Verilog, VHDL, Arduino, LabVIEW, Mojo, Carbon, D, Tcl, Awk, Sed, GraphQL
4: ALGOL, APL, J, K, Q, Forth, PostScript, Simula, Modula-2, Oberon, Eiffel, Self, Io, Rebol, Red, Factor, Joy, Idris, Agda, Coq/Rocq, Lean, Isabelle, Standard ML/SML, Miranda, Clean, Mercury, Curry, Oz, Pony, Chapel, Fortress, X10, Occam, Gleam, Roc, Vale, Odin, Jai, V, Hare, Janet, Fennel, Hy, Wren, Squirrel, AngelScript, ChaiScript, Pike, Icon, Unicon, SNOBOL, PL/I, RPG, JCL, MUMPS/M, Clipper, dBase, FoxPro, PowerBuilder, Progress/OpenEdge, Magik, Rexx, AppleScript, HyperTalk, Lingo, Inform, ZIL, AutoHotkey, AutoIt, Batch, Q#, OpenCL, CUDA, GLSL, HLSL, WebAssembly/Wasm, Reason/ReasonML, ReScript, LiveScript, Opa, Ballerina, Bosque
5: Brainfuck/Brainf, Malbolge, Whitespace, Befunge, INTERCAL, Piet, Shakespeare, Chef, LOLCODE, Ook, Unlambda, Thue, False, Velato, ArnoldC, Rockstar, Emojicode, Cow, Deadfish, HQ9+, Glass, Fractran, Funge-98, JSFuck, Plankalkul, Short Code, Autocode, FLOW-MATIC, A-0, IPL, COMIT, JOVIAL, NELIAC, MAD, TRAC, GPSS, SIMSCRIPT, Refal
` });

topic({ id: 'clouds', name: 'Clouds', noun: 'type of cloud', icon: '☁️', level: 3, q: 'Name a **type of cloud**.', strip: ['cloud', 'clouds'], list: `
1: Cumulus, Cirrus, Stratus, Rain Cloud, Storm Cloud, Thundercloud
2: Cumulonimbus, Nimbus, Nimbostratus, Altostratus, Altocumulus, Cirrostratus, Cirrocumulus, Stratocumulus, Fog, Mist, Contrail
3: Mammatus, Lenticular, Shelf Cloud/Arcus, Wall Cloud, Roll Cloud, Funnel Cloud, Anvil/Incus, Noctilucent, Nacreous/Mother of Pearl/Polar Stratospheric, Mackerel Sky, Pileus/Cap Cloud, Cumulus Congestus/Towering Cumulus, Pyrocumulus/Fire Cloud, Kelvin-Helmholtz/Wave Cloud, Asperitas, Fallstreak Hole/Hole Punch Cloud, Virga, Scud, Banner Cloud, Orographic Cloud
4: Fractus, Humilis, Mediocris, Calvus, Capillatus, Castellanus, Floccus, Fibratus, Uncinus, Spissatus, Nebulosus, Stratiformis, Undulatus, Radiatus, Lacunosus, Duplicatus, Translucidus, Perlucidus, Opacus, Intortus, Vertebratus, Praecipitatio, Tuba, Velum, Pannus, Cauda, Murus, Flumen, Fluctus, Cavum, Homogenitus, Flammagenitus, Silvagenitus, Cataractagenitus, Morning Glory Cloud, Hector, Cloud Street
5: Pyrocumulonimbus/Flammagenitus Cumulonimbus, Volutus, Mamma, Homomutatus, Polar Mesospheric Cloud
` });

topic({ id: 'rivers', name: 'Rivers', noun: 'river', icon: '🏞️', level: 3, q: 'Name a **river**.', strip: ['river', 'the'], list: `
1: Nile, Amazon, Mississippi, Thames, Yangtze
2: Danube, Rhine, Seine, Ganges, Mekong, Volga, Congo, Niger, Zambezi, Colorado, Missouri, Hudson, Rio Grande, Euphrates, Tigris, Jordan, Yellow River/Huang He, Indus, St Lawrence, Mersey, Severn, Tyne, Tiber, Shannon, Ohio
3: Loire, Rhone, Elbe, Oder, Vistula, Dnieper, Don, Ural, Ob, Yenisei, Lena, Amur, Irtysh, Brahmaputra, Irrawaddy, Salween, Chao Phraya, Red River, Pearl River, Murray, Darling, Parana, Orinoco, Sao Francisco, Uruguay, Paraguay, Magdalena, Yukon, Mackenzie, Columbia, Snake, Fraser, Arkansas, Tennessee, Potomac, Delaware, Susquehanna, Sacramento, Rio Negro, Madeira, Orange, Limpopo, Senegal, Gambia, Blue Nile, White Nile, Po, Arno, Ebro, Tagus/Tejo, Douro, Guadalquivir, Garonne, Dordogne, Meuse, Moselle, Main, Neckar, Inn, Spree, Tay, Clyde, Forth, Dee, Trent, Avon, Ouse, Wye, Tamar, Liffey, Lagan
4: Kolyma, Indigirka, Yana, Pechora, Northern Dvina, Kama, Oka, Pripyat, Dniester, Prut, Siret, Tisza, Drava, Sava, Morava, Maritsa, Struma, Vardar, Kura, Aras, Amu Darya, Syr Darya, Helmand, Sutlej, Chenab, Jhelum, Ravi, Beas, Yamuna, Godavari, Krishna, Kaveri, Narmada, Tapti, Mahanadi, Hooghly, Padma, Meghna, Teesta, Karnali, Kosi, Tonle Sap, Mahakam, Kapuas, Fly, Sepik, Waikato, Clutha, Whanganui, Murrumbidgee, Lachlan, Swan, Derwent, Ucayali, Maranon, Putumayo, Japura, Purus, Jurua, Xingu, Tapajos, Tocantins, Araguaia, Pilcomayo, Bermejo, Salado, Biobio, Atrato, Cauca, Usumacinta, Grijalva, Lerma, Balsas, Pecos, Platte, Brazos, Wabash, Cumberland, Allegheny, Monongahela, Willamette, Klamath, Gila, Green River, Saskatchewan, Assiniboine, Ottawa, Churchill, Nelson, Back, Peace, Athabasca, Kasai, Ubangi, Sangha, Lualaba, Kafue, Rufiji, Tana, Juba, Shebelle, Awash, Okavango, Cuanza, Benue, Volta, Ogooue, Sanaga, Chari, Draa, Moulouya, Sebou
5: Tom, Biya, Katun, Angara, Selenga, Vilyuy, Aldan, Vitim, Olenyok, Khatanga, Taz, Pur, Nadym, Mezen, Onega, Svir, Neva, Narva, Daugava, Neman, Pregolya, Warta, Bug, San, Wieprz, Narew, Bystrzyca, Vah, Hron, Mures, Olt, Jiu, Arges, Ialomita, Iskar, Yantra, Kamchiya, Aliakmonas, Achelous, Evros, Nestos, Strymonas, Axios, Piave, Adige, Brenta, Tagliamento, Isonzo, Ticino, Adda, Oglio, Mincio, Reno, Volturno, Garigliano, Ofanto, Simeto
` });

topic({ id: 'mountains', name: 'Mountains', noun: 'mountain or mountain range', icon: '🏔️', level: 3, q: 'Name a **mountain or mountain range**.', strip: ['mount', 'mountain', 'mountains', 'mt'], list: `
1: Everest/Mount Everest, Alps, Himalayas, Rocky Mountains/Rockies, Kilimanjaro/Mount Kilimanjaro, Fuji/Mount Fuji, Andes
2: K2, Mont Blanc, Matterhorn, Ben Nevis, Snowdon/Yr Wyddfa, Mount Rushmore, Mount Olympus/Olympus, Mount Vesuvius/Vesuvius, Mount Etna/Etna, Mount St Helens/St Helens, Denali/Mount McKinley, Appalachians/Appalachian Mountains, Pyrenees, Atlas Mountains/Atlas, Urals/Ural Mountains, Table Mountain, Mount Sinai/Sinai, Scafell Pike, Uluru, Mount Rainier/Rainier, Kangchenjunga, Annapurna, Aconcagua
3: Lhotse, Makalu, Cho Oyu, Dhaulagiri, Manaslu, Nanga Parbat, Gasherbrum, Broad Peak, Shishapangma, Elbrus, Eiger, Jungfrau, Monch, Dolomites, Carpathians, Apennines, Balkan Mountains, Caucasus, Zagros, Hindu Kush, Karakoram, Pamirs, Tian Shan, Altai, Kunlun, Sierra Nevada, Cascades, Coast Mountains, Brooks Range, Alaska Range, Mount Logan, Mount Whitney, Pikes Peak, Mount Hood, Mount Shasta, Grand Teton/Tetons, Mount Washington, Blue Ridge Mountains, Smoky Mountains/Great Smoky Mountains, Adirondacks, Ozarks, Black Hills, Sierra Madre, Popocatepetl, Orizaba/Pico de Orizaba, Chimborazo, Cotopaxi, Huascaran, Illimani, Fitz Roy, Torres del Paine, Mount Kenya, Ruwenzori/Rwenzori, Drakensberg, Mount Cameroon, Mount Kosciuszko, Aoraki/Mount Cook, Mount Taranaki, Ruapehu, Mauna Kea, Mauna Loa, Kilauea, Krakatoa, Pinatubo, Mount Ararat/Ararat, Mount Kailash, Mount Hermon, Cairngorms, Grampians, Brecon Beacons/Bannau Brycheiniog, Pennines, Snowdonia/Eryri, Mourne Mountains, Carrauntoohil, Croagh Patrick, Slieve Donard, Helvellyn, Skiddaw, Pen y Fan, Ben Macdui, Mount Teide/Teide, Zugspitze, Grossglockner, Triglav, Musala, Mount Athos, Vosges, Jura, Black Forest, Harz, Sudetes, Tatras, Scandinavian Mountains, Galdhopiggen, Kebnekaise, Mount Erebus, Vinson/Vinson Massif, Transantarctic Mountains
4: Masherbrum, Rakaposhi, Tirich Mir, Noshaq, Ismoil Somoni, Lenin Peak, Khan Tengri, Jengish Chokusu/Pobeda, Muztagh Ata, Kongur, Minya Konka/Gongga, Namcha Barwa, Gyala Peri, Kula Kangri, Jomolhari, Ama Dablam, Pumori, Nuptse, Baruntse, Kamet, Nanda Devi, Trisul, Shivling, Meru, Changabang, Kedarnath, Bandarpunch, Saltoro Kangri, Saser Kangri, Stok Kangri, Kazbek, Ushba, Shkhara, Dykh-Tau, Koshtan-Tau, Damavand, Alam Kuh, Sabalan, Toubkal, Ras Dashen, Mount Elgon, Mount Meru, Mount Stanley, Mount Speke, Thabana Ntlenyana, Mafadi, Emi Koussi, Tahat, Mount Kinabalu, Puncak Jaya/Carstensz Pyramid, Mount Wilhelm, Mount Apo, Mount Mayon/Mayon, Mount Bromo/Bromo, Semeru, Merapi, Rinjani, Agung, Tambora, Fansipan, Doi Inthanon, Hkakabo Razi, Yushan/Jade Mountain, Hallasan, Paektu/Baekdu, Mount Tate, Hotaka, Yarigatake, Kita, Ontake, Aso, Sakurajima, Ojos del Salado, Monte Pissis, Llullaillaco, Tupungato, Mercedario, Sajama, Ancohuma, Alpamayo, Siula Grande, Yerupaja, Ausangate, Salkantay, Misti/El Misti, Coropuna, Nevado del Ruiz, Pico Cristobal Colon, Pico Bolivar, Roraima, Pico da Neblina, Iztaccihuatl, Nevado de Toluca, Tajumulco, Chirripo, Pico Duarte, Blue Mountain Peak, Mount Saint Elias, Mount Lucania, Mount Foraker, Mount Hunter, Mount Robson, Mount Assiniboine, Mount Waddington, Mount Columbia, Mount Elbert, Longs Peak, Maroon Bells, Half Dome, El Capitan, Mount Katahdin, Mount Mitchell, Clingmans Dome, Stone Mountain, Mount Monadnock, Mount Marcy, Mount Mansfield, Wind River Range, Bighorn Mountains, Wasatch, Uinta, San Juan Mountains, Sangre de Cristo, Chugach, Wrangell, Saint Elias Mountains, Torngat Mountains, Laurentians, Chic-Chocs, Long Range Mountains
5: Gangkhar Puensum, Mount Tyree, Mount Shinn, Mount Kirkpatrick, Mount Markham, Mount Sidley, Mount Hampton, Big Ben/Mawson Peak, Mount Ross, Pico Basile, Mount Nimba, Mount Mulanje/Sapitwa, Mount Karisimbi, Mount Muhabura, Nyiragongo, Ol Doinyo Lengai, Mount Hanang, Kinyeti, Jebel Marra, Nelion, Point Lenana, Kibo, Mawenzi, Shira, Uhuru Peak, Gunnbjorn Fjeld, Petermann Peak, Hvannadalshnukur, Oraefajokull, Snaefellsjokull, Hekla, Katla, Eyjafjallajokull, Grimsvotn, Askja, Herdubreid, Glittertind, Store Skagastolstind, Snohetta, Halti, Saana, Pallastunturi, Hoverla, Rysy, Gerlachovsky Stit, Sniezka, Moldoveanu, Negoiu, Vihren, Botev, Korab, Maja Jezerce, Durmitor, Bobotov Kuk, Maglic, Dinara, Prokletije
` });

topic({ id: 'shakespeare', name: 'Shakespeare', noun: 'Shakespeare play', icon: '🎭', level: 3, q: 'Name a **play by Shakespeare**.', list: `
1: Romeo and Juliet, Hamlet, Macbeth
2: A Midsummer Night's Dream/Midsummer Night's Dream, Othello, King Lear, Julius Caesar, The Tempest/Tempest, Twelfth Night, Much Ado About Nothing, The Merchant of Venice/Merchant of Venice
3: As You Like It, The Taming of the Shrew/Taming of the Shrew, Antony and Cleopatra, Richard III, Henry V, The Winter's Tale/Winters Tale, The Comedy of Errors/Comedy of Errors, Measure for Measure, The Merry Wives of Windsor/Merry Wives of Windsor, Henry IV/Henry IV Part 1/Henry IV Part 2, Richard II, Coriolanus, Titus Andronicus, All's Well That Ends Well/Alls Well That Ends Well, Love's Labour's Lost/Loves Labours Lost
4: Cymbeline, Pericles/Pericles Prince of Tyre, Timon of Athens, Troilus and Cressida, The Two Gentlemen of Verona/Two Gentlemen of Verona, King John, Henry VI/Henry VI Part 1/Henry VI Part 2/Henry VI Part 3, Henry VIII
5: The Two Noble Kinsmen/Two Noble Kinsmen, Edward III, Sir Thomas More, Cardenio, Love's Labour's Won/Loves Labours Won
` });

topic({ id: 'rocks', name: 'Rocks & Minerals', noun: 'rock or mineral', icon: '🪨', level: 3, q: 'Name a **rock or mineral**.', list: `
1: Granite, Marble, Chalk, Sandstone, Limestone, Coal, Diamond, Quartz, Gold
2: Slate, Basalt, Obsidian, Pumice, Flint, Clay, Shale, Gravel, Salt/Rock Salt/Halite, Graphite, Iron Ore, Crystal, Gypsum, Talc, Amethyst, Mica, Feldspar, Lava Rock, Fossil
3: Igneous, Sedimentary, Metamorphic, Gneiss, Schist, Quartzite, Conglomerate, Breccia, Mudstone, Siltstone, Dolomite, Travertine, Tufa, Tuff, Andesite, Rhyolite, Diorite, Gabbro, Peridotite, Serpentinite, Soapstone, Jasper, Agate, Onyx, Chert, Jet, Amber, Calcite, Fluorite, Pyrite, Galena, Hematite, Magnetite, Malachite, Azurite, Bauxite, Cinnabar, Corundum, Topaz, Beryl, Garnet, Olivine, Tourmaline, Zircon, Apatite, Orthoclase, Kaolinite, Barite, Sulfur/Sulphur, Copper, Silver, Platinum, Geode, Meteorite, Asbestos, Borax, Celestine/Celestite, Selenite, Desert Rose, Lodestone
4: Phyllite, Hornfels, Eclogite, Granulite, Migmatite, Mylonite, Amphibolite, Greenschist, Blueschist, Skarn, Marl, Greywacke/Graywacke, Arkose, Coquina, Oolite, Evaporite, Laterite, Komatiite, Kimberlite, Lamproite, Carbonatite, Syenite, Monzonite, Tonalite, Trondhjemite, Dunite, Pyroxenite, Anorthosite, Dacite, Trachyte, Phonolite, Scoria, Ignimbrite, Pegmatite, Aplite, Porphyry, Diabase/Dolerite, Norite, Spilite, Hornblende, Augite, Biotite, Muscovite, Chlorite, Epidote, Staurolite, Kyanite, Sillimanite, Andalusite, Wollastonite, Tremolite, Actinolite, Glaucophane, Jadeite, Nephrite, Rhodochrosite, Smithsonite, Sphalerite, Chalcopyrite, Bornite, Cuprite, Chalcocite, Stibnite, Molybdenite, Wolframite, Scheelite, Cassiterite, Rutile, Ilmenite, Chromite, Uraninite/Pitchblende, Monazite, Spodumene, Lepidolite, Zeolite, Opal, Chalcedony
5: Tektite, Fulgurite, Moldavite, Hydroxylapatite, Kernite, Ulexite/TV Rock, Colemanite, Trona, Sylvite, Carnallite, Kieserite, Polyhalite, Anhydrite, Aragonite, Strontianite, Witherite, Cerussite, Anglesite, Wulfenite, Vanadinite, Pyromorphite, Mimetite, Crocoite, Dioptase, Chrysocolla, Turquoise, Variscite, Wavellite, Autunite, Torbernite, Carnotite, Erythrite, Annabergite, Realgar, Orpiment, Proustite, Pyrargyrite, Tetrahedrite, Enargite, Covellite, Benitoite, Painite, Taaffeite, Jadarite, Bridgmanite, Ringwoodite, Wadsleyite, Stishovite, Coesite, Lonsdaleite
` });

topic({ id: 'knots', name: 'Knots', noun: 'knot', icon: '🪢', level: 3, q: 'Name a **type of knot**.', strip: ['knot'], list: `
1: Reef Knot/Square Knot, Granny Knot, Bow/Bow Knot, Slip Knot, Overhand Knot/Overhand
2: Figure Eight/Figure of Eight/Figure 8, Bowline, Clove Hitch, Sheet Bend, Half Hitch, Two Half Hitches, Double Knot, Windsor/Windsor Knot, Half Windsor, Hangman's Knot/Noose, Shoelace Knot/Shoe Knot, Timber Hitch, Round Turn and Two Half Hitches
3: Sheepshank, Fisherman's Knot, Double Fisherman's, Trucker's Hitch, Taut-Line Hitch, Prusik, Alpine Butterfly/Butterfly, Monkey's Fist, Running Bowline, Cleat Hitch, Highwayman's Hitch, Constrictor Knot, Rolling Hitch, Cow Hitch/Lark's Head, Water Knot, Surgeon's Knot, Improved Clinch Knot/Clinch Knot, Palomar Knot, Blood Knot, Uni Knot, Zeppelin Bend, Carrick Bend, Lariat Loop/Honda Knot, Four in Hand, Pratt Knot, Eldredge Knot, Trinity Knot, Celtic Knot, Turk's Head, Bimini Twist, Diamond Knot, Stopper Knot, Figure Eight Loop, Double Bowline, Bowline on a Bight, Spanish Bowline, Marlinspike Hitch, Munter Hitch/Italian Hitch, Klemheist, Bachmann, Girth Hitch, Anchor Hitch/Fisherman's Bend, Buntline Hitch, Pile Hitch, Icicle Hitch, Gordian Knot
4: Ashley Stopper Knot, Stevedore Knot, Matthew Walker Knot, Wall Knot, Crown Knot, Manrope Knot, Sennit, Hunter's Bend/Rigger's Bend, Ashley Bend, Adjustable Grip Hitch, Farrimond Friction Hitch, Siberian Hitch, Halyard Hitch, Camel Hitch, Magnus Hitch, Picket Line Hitch, Mooring Hitch, Tumble Hitch, Waggoner's Hitch, Packer's Knot, Butcher's Knot, Miller's Knot, Bag Knot, Strangle Knot, Jug Sling Knot, Hackamore, Bottle Sling, Cat's Paw, Blackwall Hitch, Midshipman's Hitch, Englishman's Knot, Dropper Loop, Perfection Loop, Nail Knot, Albright Knot, Arbor Knot, Snell Knot, San Diego Jam Knot, FG Knot, Alberto Knot, Yosemite Bowline, Water Bowline, Portuguese Bowline, French Bowline, Tensionless Hitch, Distel Hitch, Valdotain Tresse/VT, Blake's Hitch, Schwabisch Hitch, Balthazar Knot, Merovingian Knot, Ediety Knot, Cavendish Knot, Hanover Knot, Kelvin Knot, Christensen Knot, Shelby Knot, Onassis Knot, Oriental Knot
5: Simple Simon Under, Simple Simon Over, Carrick Mat, Ocean Plait Mat, Prolong Knot, Thump Mat, Vice Versa Bend, Poldo Tackle, Gleipnir, Ossel Hitch, Ossel Knot, Pedigree Cow Hitch, Rat-Tail Stopper, Boom Hitch, Chain Sinnet/Daisy Chain, Shamrock Knot, Pipa Knot, Pan Chang Knot, Good Luck Knot, Mystic Knot, Dragonfly Knot, Josephine Knot, Agemaki, Hana Musubi
` });

topic({ id: 'cardgames', name: 'Card Games', noun: 'card game', icon: '🃏', level: 3, q: 'Name a **card game** you can play with a normal deck.', list: `
1: Poker, Snap, Go Fish, Solitaire/Patience, Blackjack/Twenty One/Pontoon, War, Old Maid, Crazy Eights
2: Rummy/Gin Rummy/Gin, Bridge, Hearts, Spades, Cheat/BS/I Doubt It, Slapjack, Speed/Spit, Spoons, Texas Hold'em/Texas Holdem, Baccarat, Cribbage, Canasta, President/Scum/Arsehole, Beggar My Neighbour/Beggar Thy Neighbor, Snip Snap Snorum, Pairs/Memory/Concentration, Freecell, Spider Solitaire/Spider, Klondike, Pyramid, Whist, Euchre, Pinochle, Rummy 500/500 Rum, Kings Corner, Egyptian Ratscrew/Egyptian Rat Screw, Nertz, Pig, Kemps, Mau Mau, Sevens/Fan Tan/Domino
3: Omaha, Seven Card Stud, Five Card Draw, Three Card Brag/Brag, Three Card Poker, Pai Gow Poker, Caribbean Stud, Bezique, Piquet, Ecarte, Skat, Doppelkopf, Schafkopf, Jass, Belote, Tarot/French Tarot, Scopa, Briscola, Tressette, Sette e Mezzo, Escoba, Mus, Brisca, Truco, Chinchon, Durak, Preferans, Bura, Tysiacha/Thousand, 500/Five Hundred, Oh Hell/Oh Heck/Up and Down the River, Nap/Napoleon, Pitch/Setback, Forty-Fives/45s, Spoil Five, Twenty-Five, All Fours, Cassino, Sheepshead, Klaberjass/Klob, Hand and Foot, Golf, Pounce, Clock Patience/Clock, Golf Solitaire, TriPeaks, Yukon, Forty Thieves, Scorpion, Accordion, Canfield, Calculation, Daifugo, Big Two/Choi Dai Di, Tien Len, Zheng Shangyou, Dou Dizhu, Shengji/Tractor, Tong-its, Pusoy Dos, Lucky Nine, Teen Patti, Rang, Twenty-Eight/28, Court Piece, Mendikot, Kalabriasz, Tute, Julepe, Burro, Ronda, Racing Demon/Russian Bank, Double Solitaire, Chase the Ace/Screw Your Neighbor, Cuckoo, Ranter-Go-Round, Newmarket/Michigan, Stops, Pope Joan, Commerce, Loo, Authors, Donkey, Switch, Black Maria, Black Lady, Knockout Whist, German Whist, Bid Whist, Solo Whist, Boston, Vint, Spite and Malice/Cat and Mouse
4: Bourre, Bouillotte, Brelan, Primero, Gleek, Ombre, Tresillo, Manille, Mariage, Sixty-Six/66, Schnapsen, Gaigel, Binokel, Elfern, Rams, Mauscheln, Tarock, Konigrufen, Cego, Zwanzigerrufen, Tapp, Bauernschnapsen, Watten, Perlaggen, Bieten, Differenzler, Schieber, Coinche/Contree, Aluette, Pishti, Batak, Bastra, Concina, Scopone, Cucu, Stoppa, Mercante in Fiera, Ciapanò, Rubamazzo, Asino, Burraco, Scala Quaranta, Pinnacola, Machiavelli, Ramino, Klabberjas, Toepen, Pandoeren, Rikken, Hartenjagen, Pesten, Kingen, Vri, Femkort, Bismarck, Plump, Chicago, Sjavs, Krypkasino, Ruff and Honours, Bid Euchre, Railroad Euchre, Buck Euchre, Call Ace Euchre, Pepper, Smear, Pusoy, Kalooki, Conquian, Panguingue/Pan, Tonk
5: Karnöffel/Karnoffel, Trappola, Minchiate, Tarocchini, Troccas, Basset, Pharo/Faro, Lansquenet, Hoca, Post and Pair, Primiera, Thirty-One/Trente et Un, Pochen, Poque, Ganjifa, Kammaraj, Cinch, Don, Phat, Ninety-Nine, Imperial, Piquet au Cent, Ulti, Zsirozas, Snapszer, Kozel, Svara, Debertz, Bai Cao, Xi Dach, Sap Xam, Phom, Bhabhi, Seep/Sweep, Do Teen Paanch, Jutpatti
` });

topic({ id: 'catbreeds', name: 'Cat Breeds', noun: 'breed of cat', icon: '🐈', level: 3, q: "What's a **breed of cat**?", strip: ['cat', 'cats', 'breed'], list: `
1: Persian, Siamese, Maine Coon, Ragdoll, Sphynx/Hairless Cat, Bengal
2: British Shorthair, Scottish Fold, Russian Blue, Abyssinian, Birman, Burmese, Norwegian Forest Cat/Norwegian Forest, American Shorthair, Exotic Shorthair, Devon Rex, Cornish Rex, Siberian, Himalayan, Savannah, Manx, Domestic Shorthair, Domestic Longhair
3: Oriental Shorthair/Oriental, Tonkinese, Egyptian Mau, Turkish Angora, Turkish Van, Bombay, Ocicat, Somali, Balinese, Chartreux, Havana Brown, Korat, Singapura, Snowshoe, Japanese Bobtail, American Curl, Selkirk Rex, LaPerm, Munchkin, Ragamuffin, Nebelung, Burmilla, Toyger, Pixie-Bob, Cymric, Peterbald, Donskoy/Don Sphynx, Kurilian Bobtail, American Bobtail, Highlander, Lykoi/Werewolf Cat, Chausie, Sokoke, Khao Manee, Thai, Ojos Azules, Colorpoint Shorthair, Javanese, Exotic Longhair, British Longhair, Scottish Straight
4: Aegean, Arabian Mau, Australian Mist, Asian Semi-Longhair/Tiffanie, Asian Shorthair, Bambino, Brazilian Shorthair, California Spangled, Ceylon, Chantilly-Tiffany, Cyprus Cat, Dragon Li/Chinese Li Hua, Dwelf, Elf Cat, European Shorthair, German Rex, Kanaani, Karelian Bobtail, Kinkalow, Mekong Bobtail, Minskin, Minuet/Napoleon, Neva Masquerade, Oregon Rex, Raas, Serengeti, Sam Sawet, Skookum, Suphalak, Tennessee Rex, Thai Lilac, Ukrainian Levkoy, Ural Rex, York Chocolate, Cheetoh, Safari, Mojave Spotted, Foldex, Genetta, Aphrodite Giant
5: Tasman Manx, Owyhee Bob, Highland Lynx, Ussuri, Jaguarundi Curl, Mandalay, Burmilla Longhair, Bristol, Lambkin, Scottish Fold Longhair/Highland Fold
` });

topic({ id: 'horsebreeds', name: 'Horse Breeds', noun: 'breed of horse', icon: '🐎', level: 3, q: "What's a **breed of horse or pony**?", strip: ['horse', 'pony', 'breed'], list: `
1: Arabian/Arab, Thoroughbred, Shetland Pony/Shetland, Clydesdale, Mustang, Quarter Horse/American Quarter Horse
2: Appaloosa, Shire, Friesian, Pinto, Paint Horse/Paint, Palomino, Welsh Pony/Welsh Cob, Andalusian, Lipizzaner/Lipizzan, Percheron, Morgan, Tennessee Walking Horse/Tennessee Walker, Mini Horse/Miniature Horse, Falabella, Connemara, Highland Pony, Exmoor Pony, Dartmoor Pony, New Forest Pony, Icelandic Horse/Icelandic, Fjord/Norwegian Fjord, Haflinger, Mongolian Horse, Przewalski's Horse, Standardbred, Hanoverian, Warmblood, Irish Draught, Cob, Gypsy Vanner/Gypsy Cob/Irish Cob
3: Akhal-Teke, Lusitano, Trakehner, Holsteiner, Oldenburg, Dutch Warmblood/KWPN, Selle Francais, Belgian/Brabant, Suffolk Punch, Cleveland Bay, Hackney, Fell Pony, Dales Pony, Eriskay Pony, Kerry Bog Pony, Caspian, Barb, Criollo, Paso Fino, Peruvian Paso, Missouri Fox Trotter, Rocky Mountain Horse, American Saddlebred, Azteca, Mangalarga Marchador, Marwari, Kathiawari, Brumby, Waler, Australian Stock Horse, Kiger Mustang, Chincoteague Pony, Banker Horse, Sable Island Horse, Canadian Horse, Newfoundland Pony, Shagya Arabian, Knabstrupper, Frederiksborg, Gotland Pony, North Swedish Horse, Finnhorse, Noriker, Camargue, Ardennes, Breton, Comtois, Boulonnais, Poitevin, Murgese, Maremmano, Salernitano, Bardigiano, Sorraia, Garrano, Pottok, Asturcon, Losino, Mallorquin, Menorquin, Carthusian, Hispano-Arabe, Kladruber, Nonius, Furioso, Gidran, Konik, Hucul, Tarpan, Yakutian, Bashkir Curly/Curly Horse, Don, Budyonny, Orlov Trotter, Russian Heavy Draft, Vladimir Heavy Draft, Karabakh, Karabair, Kabardin, Lokai, Kazakh, Yili, Guoxia, Bhutia, Spiti, Zanskari, Manipuri Pony, Java Pony, Timor Pony, Burmese Pony, Hokkaido, Kiso, Misaki, Tokara, Yonaguni, Jeju Horse
4: Kisber Felver, Murakoz, Posavac, Bosnian Mountain Horse, Pleven, Karacabey, Malakan, Jaf, Dareshuri, Turkoman, Yamud, Tchenaran, Basseri, Bhimthadi, Deccani, Sindhi, Unmol, Chummarti, Nangchen, Riwoche, Guizhou, Ningqiang, Jinzhou, Heihe, Sanhe, Erlunchun, Wenshan, Debao, Lijiang, Zhongdian, Chakouyi, Abaga, Baise, Hequ, Sumbawa, Sandalwood Pony, Batak Pony, Gayoe, Banei, Dosanko, Taishu, Noma, Miyako, Galiceno, Florida Cracker Horse, Marsh Tacky, Spanish Mustang, Choctaw Horse, Nokota, Colonial Spanish Horse, Pryor Mountain Mustang, Cerbat, Sulphur Mustang, American Cream Draft, Spotted Saddle Horse, Racking Horse, Kentucky Mountain Saddle Horse, Mountain Pleasure Horse, McCurdy Plantation Horse, Walkaloosa, Morab, Quarab, Moyle, Colorado Ranger, Pony of the Americas, American Walking Pony, Drum Horse, Welsh Mountain Pony, Lundy Pony, Hackney Pony, Irish Sport Horse, Yorkshire Coach Horse, Norfolk Trotter, Galloway Pony
5: Skyros Pony, Pindos, Peneia, Andravida, Messara, Zakynthos, Giara Horse, Esperia Pony, Monterufoli, Persano, Pentro, Sanfratellano, Tolfetano, Catria, Calabrese, Jaca Navarra, Burguete, Hispano-Breton, Cavall Pirinenc Catala, Landais, Castillonnais, Merens, Auxois, Trait du Nord, Henson, Camarillo White, Abtenauer, Rottaler, Senner, Dülmen/Dulmen Pony, Arenberg-Nordkirchen, Lewitzer, Leutstettener, Schwarzwalder Fuchs/Black Forest Horse, Rhenish German Coldblood, Schleswig Coldblood, Sokolsky, Sztumski, Malopolski, Wielkopolski, Zemaitukas, Tori, Estonian Native, Latvian, Vyatka, Mezen, Pechora, Priob, Narym, Tuva, Altai, Buryat, Transbaikal, Tavda, Kuznetsk
` });

topic({ id: 'painters', name: 'Artists', noun: 'famous painter', icon: '🖼️', level: 3, q: 'Name a **famous painter**.', list: `
1: Leonardo da Vinci/Da Vinci/Leonardo, Picasso/Pablo Picasso, Van Gogh/Vincent van Gogh, Michelangelo, Monet/Claude Monet
2: Rembrandt, Salvador Dali/Dali, Frida Kahlo/Kahlo, Andy Warhol/Warhol, Raphael, Banksy, Matisse/Henri Matisse, Cezanne/Paul Cezanne, Renoir, Degas/Edgar Degas, Manet, Vermeer/Johannes Vermeer, Botticelli, Jackson Pollock/Pollock, Edvard Munch/Munch, Gustav Klimt/Klimt, Turner/JMW Turner, Constable/John Constable, Bob Ross, Georgia O'Keeffe/O'Keeffe, Gauguin/Paul Gauguin, Lowry/LS Lowry, Hockney/David Hockney, Seurat, Magritte/Rene Magritte, Kandinsky, Mondrian/Piet Mondrian, Roy Lichtenstein/Lichtenstein, Keith Haring, Basquiat/Jean-Michel Basquiat, Caravaggio, Titian
3: El Greco, Goya/Francisco Goya, Velazquez/Diego Velazquez, Rubens/Peter Paul Rubens, Bosch/Hieronymus Bosch, Bruegel/Brueghel, Jan van Eyck/Van Eyck, Durer/Albrecht Durer, Holbein, Giotto, Fra Angelico, Tintoretto, Veronese, Canaletto, Tiepolo, Poussin, Watteau, Fragonard, Boucher, David/Jacques-Louis David, Ingres, Delacroix, Gericault, Courbet, Millet, Corot, Pissarro, Sisley, Morisot/Berthe Morisot, Cassatt/Mary Cassatt, Caillebotte, Toulouse-Lautrec, Bonnard, Vuillard, Modigliani, Chagall/Marc Chagall, Miro/Joan Miro, Braque, Leger, Duchamp, Paul Klee/Klee, Egon Schiele/Schiele, Kokoschka, Kirchner, Franz Marc, Max Ernst, De Chirico, Edward Hopper/Hopper, Norman Rockwell, Grant Wood, Andrew Wyeth, Whistler, Sargent/John Singer Sargent, Winslow Homer, Rothko/Mark Rothko, De Kooning, Lee Krasner, Francis Bacon, Lucian Freud, Gainsborough, Reynolds/Joshua Reynolds, Hogarth, Stubbs, William Blake, Rossetti, Millais, Waterhouse, Burne-Jones, Hokusai, Hiroshige, Diego Rivera, Tamara de Lempicka, Yayoi Kusama, Damien Hirst, Tracey Emin, Gerhard Richter, Jasper Johns, Rauschenberg, Kehinde Wiley, Jenny Saville, Bridget Riley, Peter Blake, Beryl Cook, Jack Vettriano, Thomas Kinkade, Margaret Keane, Mucha/Alphonse Mucha, Arcimboldo, Artemisia Gentileschi, Sofonisba Anguissola, Judith Leyster, Rosa Bonheur, Elisabeth Vigee Le Brun, Angelica Kauffman, Hilma af Klint, Sonia Delaunay, Paula Modersohn-Becker, Kathe Kollwitz, Leonora Carrington, Remedios Varo, Dorothea Tanning, Agnes Martin, Helen Frankenthaler, Joan Mitchell, Alice Neel
4: Cimabue, Duccio, Simone Martini, Masaccio, Piero della Francesca, Uccello, Mantegna, Bellini/Giovanni Bellini, Giorgione, Correggio, Parmigianino, Pontormo, Bronzino, Carracci, Guido Reni, Guercino, Zurbaran, Murillo, Ribera, Claude Lorrain, Georges de La Tour, Le Nain, Chardin, Greuze, Hubert Robert, Rigaud, Van Dyck, Jordaens, Frans Hals, Jan Steen, Pieter de Hooch, Ruisdael, Hobbema, Cuyp, Memling, Rogier van der Weyden, Gerard David, Quentin Matsys, Lucas Cranach/Cranach, Grunewald, Altdorfer, Caspar David Friedrich, Runge, Menzel, Leibl, Bocklin, Hodler, Segantini, Sorolla, Zuloaga, Fortuny, Repin, Shishkin, Aivazovsky, Levitan, Vrubel, Malevich, Rodchenko, El Lissitzky, Goncharova, Larionov, Jawlensky, Munter, Macke, Pechstein, Nolde, Heckel, Schmidt-Rottluff, Beckmann, Dix, Grosz, Schad, Feininger, Itten, Albers, Moholy-Nagy, Schlemmer, Arp, Picabia, Tanguy, Delvaux, Ensor, Khnopff, Redon, Moreau, Puvis de Chavannes, Signac, Cross, Van Rysselberghe, Derain, Vlaminck, Dufy, Rouault, Soutine, Utrillo, Valadon, Foujita, Pascin, Kisling, Laurencin, Gris/Juan Gris, Metzinger, Gleizes, Delaunay, Kupka, Severini, Boccioni, Balla, Carra, Morandi, Sironi, Burri, Fontana, Manzoni, Twombly, Still, Newman, Motherwell, Gorky, Guston, Kline, Hofmann, Diebenkorn, Thiebaud, Ruscha, Rosenquist, Wesselmann, Indiana, Kitaj, Auerbach, Kossoff, Hodgkin, Sutherland, Nash, Spencer/Stanley Spencer, Sickert, Gwen John, Augustus John, Vanessa Bell, Duncan Grant, Ben Nicholson, Patrick Heron, Terry Frost, Lanyon, Wallis/Alfred Wallis, Sidney Nolan, Arthur Boyd, Brett Whiteley, Albert Namatjira, Tom Roberts, McCubbin, Emily Kame Kngwarreye, Colin McCahon, Rita Angus, Tom Thomson, Lawren Harris, Emily Carr, Tarsila do Amaral, Portinari, Orozco, Siqueiros, Tamayo, Botero, Lam/Wifredo Lam, Matta, Torres-Garcia, Xul Solar, Raza, Husain, Amrita Sher-Gil, Raja Ravi Varma, Qi Baishi, Xu Beihong, Zhang Daqian, Wu Guanzhong, Zao Wou-Ki, Sesshu, Sotatsu, Korin, Jakuchu, Utamaro, Kuniyoshi, Hasui, Yoshitoshi
5: Pisanello, Gentile da Fabriano, Lorenzo Monaco, Benozzo Gozzoli, Filippo Lippi, Filippino Lippi, Ghirlandaio, Perugino, Pinturicchio, Signorelli, Crivelli, Antonello da Messina, Cosme Tura, Francesco del Cossa, Ercole de Roberti, Lorenzo Lotto, Moroni, Savoldo, Sebastiano del Piombo, Rosso Fiorentino, Beccafumi, Barocci, Cigoli, Orazio Gentileschi, Elsheimer, Saenredam, Fabritius, Dou, Ter Borch, Metsu, Maes, Van Ostade, Brouwer, Teniers, Snyders, Fyt, Coorte, Ruysch, Van Huysum, Claesz, Heda, Kalf, Van der Heyden, Berckheyde, Van Goyen, Van de Velde, Avercamp, Seghers, Koninck, Hammershoi, Kroyer, Larsson/Carl Larsson, Zorn, Gallen-Kallela, Schjerfbeck, Kittelsen, Dahl, Kobke, Eckersberg, Spitzweg, Waldmuller, Makart, Amerling, Feuerbach, Marees, Thoma, Uhde, Liebermann, Corinth, Slevogt, Lesser Ury, Modersohn, Vogeler, Mackensen, Overbeck
` });

topic({ id: 'scientists', name: 'Scientists', noun: 'famous scientist', icon: '🔬', level: 3, q: 'Name a **famous scientist**.', list: `
1: Albert Einstein/Einstein, Isaac Newton/Newton, Charles Darwin/Darwin, Marie Curie/Curie, Stephen Hawking/Hawking
2: Galileo/Galileo Galilei, Nikola Tesla/Tesla, Thomas Edison/Edison, Louis Pasteur/Pasteur, Alexander Fleming/Fleming, Copernicus/Nicolaus Copernicus, Archimedes, Aristotle, Pythagoras, Rosalind Franklin, Ada Lovelace, Alan Turing/Turing, Michael Faraday/Faraday, Gregor Mendel/Mendel, Jane Goodall, David Attenborough, Carl Sagan, Neil deGrasse Tyson, Richard Feynman/Feynman, Niels Bohr/Bohr, Kepler/Johannes Kepler, Benjamin Franklin, Brian Cox, Bill Nye, Alexander Graham Bell, James Watt, Watson and Crick/James Watson/Francis Crick, Oppenheimer/Robert Oppenheimer, Max Planck/Planck
3: Dmitri Mendeleev/Mendeleev, Ernest Rutherford/Rutherford, James Clerk Maxwell/Maxwell, Werner Heisenberg/Heisenberg, Erwin Schrodinger/Schrodinger, Paul Dirac/Dirac, Enrico Fermi/Fermi, Robert Hooke/Hooke, Robert Boyle/Boyle, Antoine Lavoisier/Lavoisier, John Dalton/Dalton, Amedeo Avogadro/Avogadro, Alessandro Volta/Volta, Andre-Marie Ampere/Ampere, Georg Ohm/Ohm, Heinrich Hertz/Hertz, Wilhelm Rontgen/Roentgen, Henri Becquerel/Becquerel, Pierre Curie, JJ Thomson, Edwin Hubble/Hubble, Tycho Brahe/Brahe, Edmond Halley/Halley, William Herschel/Herschel, Caroline Herschel, Euclid, Hippocrates, Galen, Ptolemy, Eratosthenes, Avicenna/Ibn Sina, Al-Khwarizmi, Alhazen/Ibn al-Haytham, Carl Linnaeus/Linnaeus, Alfred Russel Wallace/Wallace, Edward Jenner/Jenner, Joseph Lister/Lister, Robert Koch/Koch, Florence Nightingale/Nightingale, Jonas Salk/Salk, Barbara McClintock, Dorothy Hodgkin, Lise Meitner/Meitner, Emmy Noether/Noether, Chien-Shiung Wu, Katherine Johnson, Mae Jemison, Sally Ride, Tim Berners-Lee, Grace Hopper, Charles Babbage/Babbage, John von Neumann/Von Neumann, Claude Shannon, Linus Pauling/Pauling, Rachel Carson, Mary Anning, Charles Lyell/Lyell, James Hutton/Hutton, Alfred Wegener/Wegener, Ivan Pavlov/Pavlov, Sigmund Freud/Freud, Jennifer Doudna, Peter Higgs/Higgs, Roger Penrose/Penrose, George Washington Carver, Gottfried Leibniz/Leibniz, Blaise Pascal/Pascal, Rene Descartes/Descartes, Leonhard Euler/Euler, Carl Friedrich Gauss/Gauss, Alexander von Humboldt/Humboldt, Humphry Davy, Joseph Priestley, Henry Cavendish, Christiaan Huygens/Huygens, Antonie van Leeuwenhoek/Leeuwenhoek, Richard Dawkins/Dawkins, James Lovelock, Fritz Haber, Subrahmanyan Chandrasekhar/Chandrasekhar, CV Raman/Raman, Srinivasa Ramanujan/Ramanujan, Hideki Yukawa, Tu Youyou
4: Ludwig Boltzmann/Boltzmann, Josiah Willard Gibbs/Gibbs, Rudolf Clausius/Clausius, Sadi Carnot/Carnot, Lord Kelvin/Kelvin/William Thomson, James Joule/Joule, Hans Christian Orsted/Oersted, Joseph Henry, Augustin Fresnel/Fresnel, Thomas Young, Christian Doppler/Doppler, Ernst Mach/Mach, Hendrik Lorentz/Lorentz, Pieter Zeeman, Heike Kamerlingh Onnes, Wolfgang Pauli/Pauli, Max Born/Born, Louis de Broglie/De Broglie, Arthur Compton/Compton, Satyendra Nath Bose/Bose, Lev Landau/Landau, Pyotr Kapitsa, Andrei Sakharov, Igor Kurchatov, Edward Teller, Leo Szilard, Eugene Wigner, Hans Bethe, Freeman Dyson, Murray Gell-Mann, Steven Weinberg, Abdus Salam, Sheldon Glashow, Yoichiro Nambu, Chen Ning Yang, Tsung-Dao Lee, Kip Thorne, Vera Rubin, Henrietta Leavitt, Annie Jump Cannon, Cecilia Payne-Gaposchkin, Jocelyn Bell Burnell, Fred Hoyle, Georges Lemaitre/Lemaitre, Arthur Eddington, Karl Schwarzschild, Harlow Shapley, Clyde Tombaugh, Gerard Kuiper, Jan Oort, Percival Lowell, Giovanni Cassini, Ole Romer, Urbain Le Verrier, John Couch Adams, Friedrich Bessel, Joseph von Fraunhofer, Gustav Kirchhoff, Robert Bunsen, August Kekule, Friedrich Wohler, Justus von Liebig, Jons Jacob Berzelius, Svante Arrhenius, Wilhelm Ostwald, Walther Nernst, Otto Hahn, Fritz Strassmann, Irene Joliot-Curie, Frederic Joliot, Glenn Seaborg, Ernest Lawrence, Luis Alvarez, Emilio Segre, Rosalyn Yalow, Gertrude Elion, Rita Levi-Montalcini, Santiago Ramon y Cajal/Ramon y Cajal, Camillo Golgi, Rudolf Virchow, Paul Ehrlich, Emil von Behring, Elie Metchnikoff, Karl Landsteiner, Frederick Banting, Charles Best, Howard Florey, Ernst Chain, Selman Waksman, Albert Sabin, Frederick Sanger, Kary Mullis, Craig Venter, Francis Collins, Emmanuelle Charpentier, Katalin Kariko, Thomas Hunt Morgan, Theodosius Dobzhansky, Ronald Fisher, JBS Haldane, Sewall Wright, Ernst Haeckel, Jean-Baptiste Lamarck/Lamarck, Georges Cuvier/Cuvier, Richard Owen, Thomas Huxley, Louis Agassiz, Gilbert White, Konrad Lorenz, Niko Tinbergen, Karl von Frisch, EO Wilson, Lynn Margulis, Dian Fossey, Birute Galdikas, Wangari Maathai
5: Ibn al-Nafis, Al-Biruni, Al-Razi/Rhazes, Jabir ibn Hayyan, Omar Khayyam, Nasir al-Din al-Tusi, Ulugh Beg, Aryabhata, Brahmagupta, Bhaskara, Zhang Heng, Shen Kuo, Su Song, Zu Chongzhi, Hypatia, Hero of Alexandria, Anaximander, Thales, Democritus, Empedocles, Theophrastus, Aristarchus, Hipparchus, Herophilus, Erasistratus, Vesalius, William Harvey, Paracelsus, Ambroise Pare, Girolamo Fracastoro, Marcello Malpighi, Jan Swammerdam, Francesco Redi, Lazzaro Spallanzani, Luigi Galvani, Evangelista Torricelli, Otto von Guericke, Denis Papin, Daniel Bernoulli, Pierre-Simon Laplace, Joseph-Louis Lagrange, Augustin-Louis Cauchy, Evariste Galois, Sofia Kovalevskaya, Sophie Germain, Emilie du Chatelet, Maria Sibylla Merian, Margaret Cavendish, Hertha Ayrton, Inge Lehmann, Marie Tharp, Kathleen Lonsdale, Ida Noddack, Marguerite Perey, Harriet Brooks, Esther Lederberg, Nettie Stevens, Alice Ball, Percy Julian, Ernest Everett Just, Charles Drew, Daniel Hale Williams
` });

topic({ id: 'presidents', name: 'US Presidents', noun: 'US president', icon: '🏛️', level: 3, q: 'Name a **president of the United States**.', strip: ['president'], list: `
1: George Washington/Washington, Abraham Lincoln/Lincoln, Barack Obama/Obama, Donald Trump/Trump, Joe Biden/Biden
2: John F Kennedy/JFK/Kennedy, Thomas Jefferson/Jefferson, Theodore Roosevelt/Teddy Roosevelt, Franklin D Roosevelt/FDR/Franklin Roosevelt, Ronald Reagan/Reagan, Bill Clinton/Clinton, George W Bush, George HW Bush/George Bush/Bush, Richard Nixon/Nixon, Jimmy Carter/Carter
3: John Adams, John Quincy Adams, James Madison/Madison, James Monroe/Monroe, Andrew Jackson/Jackson, Ulysses S Grant/Grant, Dwight D Eisenhower/Eisenhower/Ike, Harry S Truman/Truman, Lyndon B Johnson/LBJ, Gerald Ford/Ford, Woodrow Wilson/Wilson, Herbert Hoover/Hoover, Calvin Coolidge/Coolidge, William McKinley/McKinley, Andrew Johnson, James K Polk/Polk
4: Martin Van Buren/Van Buren, William Henry Harrison, John Tyler/Tyler, Zachary Taylor/Taylor, Millard Fillmore/Fillmore, Franklin Pierce/Pierce, James Buchanan/Buchanan, Rutherford B Hayes/Hayes, James A Garfield/Garfield, Chester A Arthur/Chester Arthur, Grover Cleveland/Cleveland, Benjamin Harrison, William Howard Taft/Taft, Warren G Harding/Harding
` });

topic({ id: 'greek', name: 'Greek Alphabet', noun: 'Greek letter', icon: '🔣', level: 3, q: 'Name a **letter of the Greek alphabet**.', list: `
1: Alpha, Beta, Pi, Omega, Delta
2: Gamma, Sigma, Theta, Lambda, Epsilon, Mu
3: Zeta, Eta, Iota, Kappa, Nu, Xi, Omicron, Rho, Tau, Upsilon, Phi, Chi, Psi
5: Digamma, Koppa, Sampi, San, Heta, Stigma
` });

topic({ id: 'composers', name: 'Composers', noun: 'classical composer', icon: '🎼', level: 3, q: 'Name a **classical composer**.', list: `
1: Mozart, Beethoven, Bach, Vivaldi
2: Tchaikovsky, Chopin, Handel, Haydn, Brahms, Schubert, Debussy, Wagner, Verdi, Strauss/Johann Strauss, Holst, Elgar, Mendelssohn, Pachelbel, Rachmaninoff/Rachmaninov, Stravinsky, Puccini, Grieg, Rossini, Dvorak, Liszt, Schumann, Saint-Saens, Ravel, Mahler, Satie, John Williams, Hans Zimmer
3: Prokofiev, Shostakovich, Rimsky-Korsakov, Mussorgsky, Borodin, Sibelius, Bizet, Faure, Berlioz, Offenbach, Gounod, Massenet, Delibes, Vaughan Williams, Purcell, Britten, Tallis, Byrd, Monteverdi, Palestrina, Scarlatti, Telemann, Corelli, Albinoni, Gluck, Paganini, Bruckner, Richard Strauss, Smetana, Janacek, Bartok, Kodaly, Copland, Gershwin, Bernstein, Barber, Philip Glass, Steve Reich, John Adams, Arvo Part, Gorecki, Einaudi, Karl Jenkins, John Rutter, Delius, Walton, Tippett, Finzi, Butterworth, Parry, Stanford, Sullivan/Arthur Sullivan, Lloyd Webber/Andrew Lloyd Webber, Hildegard von Bingen, Clara Schumann, Fanny Mendelssohn, Lili Boulanger, Nadia Boulanger, Amy Beach, Florence Price, Scott Joplin, Ennio Morricone, Howard Shore, John Barry, Danny Elfman, Hisaishi/Joe Hisaishi, Ligeti, Messiaen, Boulez, Stockhausen, Schoenberg, Berg, Webern, Cage/John Cage, Ives, Hindemith, Weill, Orff, Respighi, Mascagni, Leoncavallo, Bellini, Donizetti, Weber, Meyerbeer, Glinka, Scriabin, Khachaturian, Villa-Lobos, Piazzolla, Ginastera, Albeniz, Granados, De Falla/Manuel de Falla, Rodrigo, Nielsen, Lully, Rameau, Couperin, Charpentier, Buxtehude, Pergolesi, Boccherini, Clementi, Hummel, Czerny, Salieri, Field/John Field
4: Dufay, Ockeghem, Josquin/Josquin des Prez, Machaut, Perotin, Leonin, Dunstable, Obrecht, Isaac, Lassus, Victoria, Morales, Gesualdo, Gabrieli, Sweelinck, Schutz, Frescobaldi, Froberger, Biber, Zelenka, Tartini, Locatelli, Geminiani, Quantz, CPE Bach, JC Bach, Stamitz, Dittersdorf, Vanhal, Pleyel, Cherubini, Spontini, Mehul, Gossec, Saint-Georges/Chevalier de Saint-Georges, Spohr, Moscheles, Kalkbrenner, Alkan, Thalberg, Gottschalk, Franck, Chausson, Duparc, d'Indy, Chabrier, Lalo, Dukas, Roussel, Koechlin, Poulenc, Milhaud, Honegger, Auric, Tailleferre, Durey, Ibert, Jolivet, Dutilleux, Xenakis, Varese, Berio, Nono, Maderna, Dallapiccola, Petrassi, Busoni, Zemlinsky, Korngold, Schreker, Pfitzner, Reger, Wolf/Hugo Wolf, Goldmark, Suk, Martinu, Fibich, Novak, Enescu, Szymanowski, Moniuszko, Lutoslawski, Penderecki, Kilar, Schnittke, Gubaidulina, Ustvolskaya, Kabalevsky, Glazunov, Lyadov, Taneyev, Arensky, Medtner, Myaskovsky, Glière, Balakirev, Cui, Dargomyzhsky, Tubin, Tormis, Rautavaara, Saariaho, Lindberg, Salonen, Berwald, Alfven, Stenhammar, Gade, Svendsen, Halvorsen, Bax, Bridge, Ireland, Howells, Rubbra, Moeran, Warlock, Quilter, Coleridge-Taylor, Smyth/Ethel Smyth, Maxwell Davies, Birtwistle, Tavener, MacMillan, Ades, Turnage, Knussen, Sousa, MacDowell, Griffes, Ruggles, Cowell, Harris, Piston, Sessions, Carter/Elliott Carter, Babbitt, Feldman, Riley/Terry Riley, La Monte Young, Corigliano, Higdon, Lang, Wolfe, Gordon, Torke, Daugherty, Takemitsu, Hosokawa, Ifukube, Yamada, Tan Dun, Chen Yi, Zhou Long, Bright Sheng, Isang Yun, Unsuk Chin
5: Philippe de Vitry, Francesco Landini, Johannes Ciconia, Gilles Binchois, Antoine Busnois, Loyset Compère, Pierre de la Rue, Jean Mouton, Nicolas Gombert, Clemens non Papa, Cipriano de Rore, Adrian Willaert, Jacob Arcadelt, Philippe Verdelot, Costanzo Festa, Luca Marenzio, Orazio Vecchi, Adriano Banchieri, Salamone Rossi, Barbara Strozzi, Francesca Caccini, Elisabeth Jacquet de La Guerre, Isabella Leonarda, Marin Marais, Sainte-Colombe, Jean-Marie Leclair, Michel Corrette, Joseph Bodin de Boismortier, Johann David Heinichen, Johann Friedrich Fasch, Christoph Graupner, Franz Benda, Carl Heinrich Graun, Johann Adolph Hasse, Niccolò Jommelli, Tommaso Traetta, Baldassare Galuppi, Giovanni Battista Sammartini, Gaetano Pugnani, Giovanni Battista Viotti, Rodolphe Kreutzer, Pierre Rode, Pierre Baillot, Jan Ladislav Dussek, Leopold Koželuch, Antonio Rosetti, Joseph Martin Kraus, Franz Xaver Richter, Ignaz Holzbauer, Christian Cannabich
` });
